### PR TITLE
PR: Comprehensive overhaul of the theme for much better flexibility, features, layout, maintainability and more

### PR DESCRIPTION
**Pull request by CAM-Gerlach**
This is it, my friends. At long last, deliverance is at hand.

In short, this overhaul makes the theme actually usable on sites other than Spyder; adds numerous new features, models, flowblocks and integrations; fixes literally dozens of layout or other bugs, greatly improves performance, security, privacy accessibility, mobile-friendliness and standards conformance, and makes the code vastly easier to maintain and add new features.

For example, adding Sponsors section which [previously required](https://github.com/spyder-ide/lektor-icon/commit/7d8259d7a197c6db48e18756ad306c3c08d9372f) hundreds of lines of changes  spread across dozens of places in 7 files can be accomplished once these changes are merged with a single, simple wrapper model (and in the future, won't even require that) either site-side or theme-side, after which everything can be done in the ``contents.lr`` or the site's admin GUI. See the [changelog](https://github.com/uah-ams/lektor-icon/blob/modularity-fixes/CHANGELOG.md) for a (relatively) brief summary of what's new and different.

If it seems like a huge task to review all this, fear not—by itself, this doesn't actually change anything on the production or develop site (though I include a procedure below to ensure the new changes aren't pulled accidentally and don't cause any problems with the CIs), and I include an example site with the theme you can test it on; the primary reviewing could be left to when the Spyder website is updated to use this version. I will follow this PR with one that adds support for the example site to be built with Travis CI to test changes and deployed to Github Pages to serve as live demo of the theme, and another PR that will add a wrapper model and perhaps a few stylesheet tweaks to allow the sponsor section to be easily added on the Spyder-Website side. 

To avoid the conflicts with the changes in support of spyder-ide/spyder-website#145 that were suddenly commited directly to the master branch this morning without a PR or review and to ensure all CIs, etc use the "legacy" version for now, I recommend the following before merging this:

1. Create a branch named ``legacy`` with its ``HEAD`` at ``503d791f`` (the current master ``HEAD``)
2. Hard ``reset`` the master branch to ``cf4bfd3a`` and force push
3. Add the line ``branch = legacy`` to the [``.gitmodules`` config file](https://github.com/spyder-ide/website-spyder/blob/develop/.gitmodules) on ``spyder-website``

Then, this PR can be merged against ``master``, followed by PRs from me adding CI/GH Pages builds and wrapper flowblock ("Sponsor" section) support in separate PRs, and finally me doing the overhaul of Spyder-Website to use this version of the theme instead (which should actually be pretty straightforward with these changes).

### CODE REVIEW

**Comment by CAM-Gerlach** [comment]
> I just have a simple question: does our website render as it is now after these changes?

It will render *exactly* the same until we explicitly change it to use the new version of the theme (with full opportunity for review and modifications then), and it will also fix the merge conflicts, if you follow the above procedure:

1. Create a branch named ``legacy`` with its ``HEAD`` at ``503d791f`` (the current master ``HEAD``) and push it to this repo
2. Hard ``reset`` the master branch to ``cf4bfd3a`` and force push
3. Add the line ``branch = legacy`` to the [``.gitmodules`` config file](https://github.com/spyder-ide/website-spyder/blob/develop/.gitmodules) on ``spyder-website``

(Or, if you want to give me admin permissions here, I can do it for you)

**Comment by ccordoba12** [comment]
Ok, I hadn't seen that. Will do when I have some free time.

**Comment by CAM-Gerlach** [comment]
Okay, great! No pressure, but any idea on an ETA so I can plan accordingly?( I have several downstream sites depending on it). You could also give me admin temporarily and I could do it for you (your or I will also need it to set up CI integration and GH pages deployment for the example site in/after next PR), but that's up to you.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 Bump, and lmk if you want me to do it. Also, you might want to consider ``git tag``-ing ``503d791f`` as ``v0.1``, ``legacy`` or something like that so its easy to keep track of the major API break in the future if/when you remove the old branch.

**Comment by ccordoba12** [comment]
> Bump, and lmk if you want me to do it

Yes, please help me with this one because I don't have time for it. Now you should have write permissions to this repo.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 Thanks. Everything is now taken care of with respect to Spyder-Website and this PR, except for merging ``develop`` to ``production`` there so the Sponsor changes go live for now.

Next steps will be setting up Travis CI to build this site to automatically check that theme changes don't break something important, as well as have a live, functioning demo of the theme online, as well as reimplementing the sponsors feature in the theme, by way of adding a container flowblock to the mainpage which will allow one section to contain any desired sub-flowblocks, opening up almost unlimited possibilities for future customization without any further changes to the theme itself.

Then, finally, we should be ready to do port the site over to the new theme and clean up the other cruft.

**Comment by ccordoba12** [comment]
I renamed the `legacy` tag to `old` because having both a tag and a branch with the same name was confusing git.

**Comment by CAM-Gerlach** [comment]
@ccordoba12 Okay, sure. Thanks.

**Pull request merged**
